---
format: html
about: 
  template: marquee
  links :
    - icon: github
      text: github
      href: https://github.com/GCAM-KAIST
---

# Professors

------------------------------------------------------------------------

### [Jiyong Eom](https://kaist-iam.github.io/group/eomjiyong.html)

Jiyong Eom is an associate professor at KAIST College of Business and the head of KAIST Graduate School of Green Growth. His research interest includes energy & environmental economics and management, integrated assessment modeling for climate policy analysis, demand-side management of electricity with ICT, and green information systems & energy informatics. His research appeared in Nature Energy, Global Environmental Change, Energy Economics, Energy Policy, Energy, Technology Forecasting & Social Change, and Climatic Change. He served as a contributing author for Chapters 6 and 9 of the IPCC Fifth Assessment Report of Working Group III (Mitigation of Climate Change) and is a 2019 Highly Cited Researcher in the social science area. He received a BS degree in Chemical Engineering from Yonsei University, a MS degree in Chemical and Biomolecular Engineering from KAIST, and a PhD degree in Management Science & Engineering with the concentration on Policy & Strategy from Stanford University.

------------------------------------------------------------------------

### [Haewon C. McJeon](https://kaist-iam.github.io/group/hmcjeon.html) <!--#  -->

Haewon McJeon is an associate professor at KAIST Graduate School of Green Growth and Sustainability. His research primarily focuses on using Integrated Assessment Models (IAM) to formulate low-carbon, carbon-neutral, and carbon-negative pathways for mitigating climate change. At KAIST Graduate School of Green Growth & Sustainability, he is teaching the next generation of modelers how to use quantitative models to evaluate decarbonization strategies in Korea and developing Asia.

Previously, he held positions at the Joint Global Change Research Institute and the Center for Global Sustainability, where he played a pivotal role in developing the Global Change Assessment Model (GCAM). In that role, he has served as the lead Integrated Assessment Modeler for two White House reports on deep decarbonization pathways (Long-Term Strategy, 2021 and Mid-Century Strategy, 2016). He has published widely on topics such as the impact of fossil fuels on climate change, decarbonization technologies, and decision-making under uncertainties. He has published over 80 papers in peer-reviewed journals, including Nature, Science, Energy Economics, and Climatic Change.

Dr. McJeon holds a Ph.D. and a Master's degree in Environmental Policy from the University of Maryland, as well as a Bachelor's degree in Economics from Seoul National University.

------------------------------------------------------------------------

### [Son H. Kim](https://kaist-iam.github.io/group/sonhkim.html)


Dr. Son H. Kim is a visiting professor at the Korea Advanced Institute of Science and Technology’s (KAIST) Graduate School of Green Growth and Sustainability (GGGS). He is on leave from the Pacific Northwest National Laboratory's (PNNL) Joint Global Change Research Institute. As a senior Earth Scientist at PNNL, he has 30 years of experience in developing and utilizing integrated assessment models that bridge the gap between the human system and the Earth's natural systems. Notably, Dr. Kim is the creator of the modeling architecture of the widely-utilized Global Change Analysis Model. Holding a PhD in nuclear engineering from the Massachusetts Institute of Technology, Dr. Kim is deeply committed to addressing global challenges, such as the energy crisis and climate change. He employs Integrated Assessment Models to analyze the multifaceted impacts of various scenarios on energy systems and the environment, seeking sustainable solutions for these pressing issues.


------------------------------------------------------------------------

# Students

------------------------------------------------------------------------

### Ahmed Sobhy Mahmoud

Ph.D. Student of Graduate School of Business & Technology Management

**Research Interest**

Demand-side management, consumer behavior, integrated assessment model, policy analysis & policy making

**Education**

M.S. Ajou University, Energy Science and Policy

M.B.A. Arab Academy for Science, Technology & Martime Transport, Joint Degree with Universitat Autonoma de Barcelona, Strategic Management

B.S. Helwan University, Mechanical Power Engineering

**Work Experience**

Project Manager, Elsewedy Electric Transmission and Distribution

Project Manager, Gulf of Suez Petroleum Company JV British Petroleum

------------------------------------------------------------------------

### Jiseok Ahn

Ph.D. Student of Graduate School of Innovation & Technology Management

**Research Interest**

Energy system modeling, integrated assessment model, energy & environmental policy

**Education**

M.S. Grenoble Institute of Technology, Electrical Engineering

B.S. Inha University, Industrial Engineering

**Work Experience**

Senior Enginer, Energy Policy Research Team, Korea Institute of Energy Research

------------------------------------------------------------------------

### Jungme Lee

M.S. Student of Graduate School of Green Growth & Sustainability

**Research Interest**

Energy system modeling, integrated assessment model, energy & environmental policy

**Education**

B.S. EHWA WOMANS University, Climate and Energy System Engineering

B.S. EHWA WOMANS University, Management for Science and Technology

------------------------------------------------------------------------

### Jiwon Kwun

M.S. Student of Graduate School of Business & Technology Management

**Research Interest**

Renewable energy, hydrogen energy, ESG strategy, sustainable finance

**Education**

B.S. Stony Brook University, Technological System Management

B.S. Stony Brook University, Applied Mathematics & Statistics

------------------------------------------------------------------------

# Alumni

------------------------------------------------------------------------

### Jeongho Jo

M.S. Green Business of Policy Program

**Research Interest**

Energy & environmental policy and management, demand-side management, energy mix, consumer behavior, ESG strategy, green business model

**Education**

B.A. Yokohama National University, Department of Business Administration (Magma Cum Laude)

**Work Experience**

Central Research Institute of Electric Power Industry (CRIEPI)
